from django.shortcuts import render
from typing import List
from dataclasses import dataclass

@dataclass
class Category:
    team_name: str
    members: List
    desc: List
    image: List

class Link:
    subs: str
    ident: str
    
def home_view(request):
    context={ 
        "merc_list":["Offense", "Defense", "Support"]
    }
    return render(request, "home.html" , context)

def merc_view(request, category):
    context= {
        'category': category ,
        
        "MD":{
                "Offense": Category(
                    "Offense",
                    ["Scout","Soldier","Pyro"],
                    [["Born and raised in Boston, Massachusetts, USA, the Scout is a symbol of everything you want to punch in the face, fast-running scrapper with a baseball bat and a snarky in-your-face attitude. He is the fastest and most mobile mercenary on the battlefield unassisted. His Double Jump leaves slower opponents such as the Heavy struggling to keep up and helps him navigate the terrain while dodging oncoming bullets and projectiles. Carrying a Scattergun, a Pistol, and a Bat, the Scout is an ideal class for aggressive fighting and flanking. The Scout is a great class for quick hit-and-run tactics that can either sap away enemies' health or kill them outright due to his ability to get in, do damage, and dash away before even being noticed. However, the Scout is tied with the Engineer, Sniper, and Spy for having the lowest health of any class, leaving him vulnerable when he is on the front line; a fair trade-off for his ability to run in and out of a contested hot-spot very quickly, letting him lead the team to victory without the other team even noticing in time.","Scunt_Dscript"],
                        ["The Soldier is a crazed, jingoistic patriot from Midwest, USA. Tough and well-armed, he is versatile, capable of both offense and defense, and a great starter class to get familiar with the game. Well-balanced and possessing both survivability and mobility, the Soldier is considered one of the most flexible classes in Team Fortress 2. Despite his low ground movement speed, he is capable of using rocket jumps to reach his destination quickly. His large health pool is second only to that of the Heavy, and his wide array of armaments and weaponry allows him to bring whatever weapon or equipment is best suited to the situation at hand.","Soldier_Dscript"],
                        ["The Pyro is a mumbling pyromaniac of indeterminate origin who has a burning passion for all things fire related. As shown in Meet the Pyro, they appear to be insane and delusional, living in a utopian fantasy world known as Pyroland. The Pyro specializes in fighting enemies at close range using a homemade Flame Thrower. Enemies set on fire suffer from afterburn and take additional damage over time, allowing them to excel at hit-and-run tactics. Due to the Flamethrowers short range, the Pyro is weaker at longer ranges and relies heavily on ambushing and taking alternate routes to catch opponents off-guard. Although categorized as an offensive class, they also bring some utility to the battlefield. The Pyros compression blast, for example, can deflect enemy projectiles, extinguish burning teammates, and forcibly reposition any enemy, including one under the effects of an invincibility-granting ÜberCharge.","Pyro_Dscript"]],
                    ["static/merc_images/scout.png","static/merc_images/soldier.png","static/merc_images/pyro.png"],
                ),

                "Defense": Category(
                    "Defense",
                    ["Demoman","Heavy","Engineer"],
                    [["The Demoman is the difficult-but-devastating master of explosives. His strength is slightly weaker than a Soldier, but a lot more powerful than most classes due to his firepower.A fierce temper, a fascination with all things explosive, and a terrible plan to kill the Loch Ness Monster cost the six year old Demoman his original set of adoptive parents. Later, back at the Crypt Grammar School for Orphans near Ullapool in the Scottish Highlands, the boy's bomb-making skills improved dramatically. His disposition and total number of intact eyeballs, however, did not.","Demo_Dscript"],
                        ["The Heavy Weapons Guy, more commonly known as the Heavy, is a towering hulk of a man hailing from the USSR. He is the largest and possibly most dangerous class in Team Fortress 2. Boasting the most default health and devastating firepower from his trusty Mini-gun, the Heavy is no pushover. The Heavy's Mini-gun can inflict heavy damage at a high rate of fire, allowing him to mow down opposing babies, cowards, and teeny-men in seconds. The Heavy's movement speed is his main weakness. Upon revving up or firing his Mini-gun, his already unimpressive speed drops down to an even lower amount, making him a very easy target for Snipers and Spies. His slow speed makes him more dependent on support from Medics and Engineers to keep him in the fight. The Heavy also takes 50 percent less knockback from damage sources, except for Sentry Gun bullets. Aside from decimating entire teams, the Heavy is able to provide further support for his comrades with an often required health boost via his Sandvich, which, when consumed, is capable of healing him to full health. It can also be dropped to provide an instant 50 percent health boost to his teammates, systematically equal to a medium health kit. However, if the Heavy is not careful, an enemy may pick up the dropped Sandvich for a health boost of their own.","Chad_Dscript"],
                        ["The Engineer is a soft-spoken, amiable Texan from Bee Cave, Texas, USA with an interest in all mechanical things. He specializes in constructing and maintaining Buildings that provide support to his team, rather than fighting at the front lines, making him the most suitable for defense. The Engineer's various gadgets include the Sentry Gun, an automated turret that fires at any enemy in range, the Dispenser, a device that restores the health and ammunition of nearby teammates, and Teleporters that quickly transport players from point A to point B. Because the Engineer's ingenious devices are under constant threat from explosives and devious enemy Spies, a good Engineer must keep his gear under a watchful eye and under repair with his Wrench at all times. When the Engineer needs to get his hands dirty, his trio of generic yet capable weapons, along with the assistance of his helpful hardware, make him more than capable of holding his own in a fight. If need be, the Engineer can even pick up and haul constructed buildings to redeploy them in more favorable locations. While usually viewed as a defensive class, the Engineer has a selection of high-tech weapons that allow him to destroy projectiles or to build faster-deploying, less damaging Sentry Guns, which give him great utility at the front lines too. His Teleporters are also a key point to both the offensive and defensive team's success, allowing slower, heavier classes to reach the front-lines quicker","Engi_Dscript"]],
                    ["static/merc_images/demo.png","static/merc_images/heavy.png","static/merc_images/engi.png"],
                 ),
                 
                "Support": Category(
                    "Support",
                    ["Medic","Sniper","Spy"],
                    [["The Medic is a Teutonic man of medicine from Stuttgart, Germany. While he may have a tenuous adherence to medical ethics, he is nonetheless the primary healing class of the team. Although the Medic's Syringe Gun and Bonesaw aren't the most excellent weapons for direct combat, he can typically still be found near the front lines, healing wounded teammates while trying to stay out of enemy fire.When the Medic focuses his Medi Gun on a teammate, they gradually regain health points. Teammates who are already at full health have their health buffed beyond the standard limit, going up to 150 percent of their base health capacity (with the exception of weapons that have overheal penalties, such as the Fists of Steel and the Quick-Fix). Teammates who have not taken damage recently are healed more rapidly, encouraging other players withdrawals when injured. When healing, the Medic gradually fills a unique ÜberCharge bar, which can fill faster if healing injured or not-fully-overhealed teammates. When the ÜberCharge bar is fully charged, the Medic's Medi-Gun begins to crackle, accompanied by small electric Team-colored particles at its tip, indicating that he can now deploy a unique charge to benefit his healing target (and himself) for eight seconds. A charge from the Medi Gun offers temporary invulnerability; a charge from the Kritzkrieg grants guaranteed critical hits; the Quick-Fix grants rapid healing, along with immunity to knockback and compression blasts from Pyros; and the Vaccinator grants enhanced damage resistance to a specific damage type (bullets, explosives, and fire).","Doctor_Dscript"],
                        ["Hailing from the lost country of New Zealand and raised in the unforgiving Australian outback, the Sniper is a tough and ready crack shot. The Sniper's main role on the battlefield is to pick off important enemy targets from afar using his Sniper Rifle and its ability to deal guaranteed critical hits with a headshot (with some exceptions). He is effective at long range, but weakens with proximity, where he is forced to use his Submachine Gun or his Kukri. As a result, the Sniper tends to perch on higher grounds or in hard-to-see places, where he can easily pin down enemies at chokepoints. Although he is typically known for instantaneously killing enemies at a distance, the Sniper can use the Huntsman to get closer to the enemy. Additionally, the Sydney Sleeper and the mysterious contents of Jarate allow him to take on a support role by causing enemies to take mini-crits","Sniper_Dscript"],
                        ["Hailing from an indeterminate region of France, the Spy is an enthusiast of sharp suits and even sharper knives. Using a unique array of cloaking watches, he can render himself invisible or even fake his own death, leaving unaware opponents off-guard. His Disguise Kit lets him take on the form of any class on either team, allowing him to blend in while behind enemy lines before stabbing his unsuspecting 'teammates' in the back. In fact, a swift backstab with any of the Spy's knives will kill most foes in a single hit - provided they aren't under the effects of any type of invulnerability, or some other form of immense damage reduction. In addition to being able to swiftly assassinate key enemies, the Spy possesses the ability to disable and destroy Engineer-constructed buildings with his Sapper. Once attached to an enemy building, the Sapper disables and slowly drains health from the building. However, a Sapper can be removed by an Engineer, or Pyro wielding the Homewrecker, Maul, or Neon Annihilator. The Spy, while disguised, has access to enemy Dispensers and Teleporters. This enables him to replenish his health and ammo behind enemy lines and navigate while blending in. Despite being disguised, the Spy still collides with enemy buildings. Medics can both heal and apply ÜberCharge effects to disguised enemy Spies. Whereas most players can only see the names and health of their teammates, the Spy can observe the names and health of the enemy team as well, allowing him to relay useful intelligence. This ability is unique to only the Spy and a Medic carrying the Solemn Vow.","Spy_Dscript"]],
                    ["static/merc_images/medic.png","static/merc_images/sniper.png","static/merc_images/spy.png"],   
                 ),
            }
    }
    return render(request, "mercs.html", context)